# Generated by Django 4.2.16 on 2024-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(default='', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='部门')),
                ('building', models.CharField(default='', max_length=15, verbose_name='楼栋')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='预算')),
                ('cachet', models.CharField(default='', max_length=200, verbose_name='公章')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学院部门',
                'verbose_name_plural': '学院/部门',
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=250, verbose_name='电影简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/images/', verbose_name='电影海报'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='电影名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(blank=True, verbose_name='电影资源链接'),
        ),
    ]
